//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aftersales
    {
        public int Id { get; set; }
        public Nullable<byte> SalesType { get; set; }
        public string Contents { get; set; }
        public string Contact { get; set; }
        public Nullable<byte> Status { get; set; }
        public string OrderNumber { get; set; }
        public System.DateTime SubTime { get; set; }
        public Nullable<byte> ProcessingStatus { get; set; }
        public Nullable<int> ProcessingPeople { get; set; }
        public string Result { get; set; }
    }
}
