//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreaData
    {
        public int Area_Id { get; set; }
        public string Area_Code { get; set; }
        public string Area_Name { get; set; }
        public int Parent_Id { get; set; }
        public int Top_Id { get; set; }
        public int Area_Level { get; set; }
        public string Area_Name_EN { get; set; }
    }
}
