//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BalanceOfPaymentsDetails
    {
        public int ID { get; set; }
        public int AboutUserId { get; set; }
        public Nullable<decimal> BPNum { get; set; }
        public string BPDescription { get; set; }
        public bool IsBORP { get; set; }
        public string AboutOrderNumber { get; set; }
        public System.DateTime AboutTime { get; set; }
        public byte BPType { get; set; }
        public byte BPWay { get; set; }
    }
}
