//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BalDetail
    {
        public int Id { get; set; }
        public Nullable<int> User_Id { get; set; }
        public string PayIP { get; set; }
        public Nullable<System.DateTime> PayTime { get; set; }
        public Nullable<double> PaySum { get; set; }
        public Nullable<byte> Pay_type { get; set; }
        public int OrderUser_Id { get; set; }
        public double GetSum { get; set; }
        public int OrderId { get; set; }
        public string BuyDetail { get; set; }
    }
}
