//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatMessage
    {
        public int Id { get; set; }
        public int SendUserId { get; set; }
        public int ReceiveUserId { get; set; }
        public string Content { get; set; }
        public System.DateTime SendTime { get; set; }
        public int ParentId { get; set; }
        public string AttachmentName { get; set; }
        public string AttachmentUrl { get; set; }
        public bool Status { get; set; }
        public bool ChatMessageIsRead { get; set; }
    }
}
