//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dly_CellsMenu
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Path { get; set; }
        public Nullable<int> Parent_Id { get; set; }
        public Nullable<int> Top_Id { get; set; }
        public Nullable<byte> Depth { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<byte> Dly_Status { get; set; }
        public string paraString { get; set; }
    }
}
