//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLY_Admin
    {
        public int Id { get; set; }
        public string Dly_UName { get; set; }
        public string Dly_UpassWord { get; set; }
        public Nullable<int> Dly_Parent { get; set; }
        public string Dly_LastLoginIP { get; set; }
        public Nullable<System.DateTime> Dly_LastLoginTime { get; set; }
        public Nullable<byte> Dly_Status { get; set; }
    }
}
