//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Edm
    {
        public int Id { get; set; }
        public int UB_Id { get; set; }
        public Nullable<bool> IsMailAct { get; set; }
        public Nullable<bool> IsMailSub { get; set; }
        public Nullable<int> U_Type { get; set; }
        public Nullable<int> IsSend { get; set; }
        public byte IsSendGoldBook { get; set; }
    }
}
