//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailBook
    {
        public int id { get; set; }
        public int userId { get; set; }
        public string bookemail { get; set; }
        public int proid { get; set; }
        public byte booktype { get; set; }
        public System.DateTime booktime { get; set; }
        public byte sendstatus { get; set; }
        public double pricedown { get; set; }
    }
}
