//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enterprise
    {
        public Enterprise()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public string EnterpriseName { get; set; }
        public Nullable<short> Location { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public Nullable<int> IndustryId { get; set; }
        public string Contacts { get; set; }
        public string Fax { get; set; }
        public string Cover { get; set; }
        public string ZipCode { get; set; }
        public string SiteURL { get; set; }
        public string Introduction { get; set; }
        public string Address { get; set; }
        public string EnterpriseName_EN { get; set; }
        public string Contacts_EN { get; set; }
        public string Introduction_EN { get; set; }
        public string Address_EN { get; set; }
        public string EnterpriseType { get; set; }
        public string EnterpriseType_EN { get; set; }
        public string MainProducts { get; set; }
        public string MainProducts_EN { get; set; }
        public string MainSales { get; set; }
        public string MainSales_EN { get; set; }
        public string EmployeeCounts { get; set; }
        public string EmployeeCounts_EN { get; set; }
        public string AnnualTurnover { get; set; }
        public string AnnualTurnover_EN { get; set; }
        public int Registeredcapital { get; set; }
        public decimal Area { get; set; }
        public string ManagementSystemcertification { get; set; }
        public string ManagementSystemcertification_EN { get; set; }
        public string ProductService { get; set; }
        public string ProductService_EN { get; set; }
        public string EnpriseRemark { get; set; }
        public string EnpriseRemark_EN { get; set; }
        public string BusinessLicenseNumber { get; set; }
        public string LegalRepresentative { get; set; }
        public string LegalRepresentative_EN { get; set; }
        public string OperationTerm { get; set; }
        public string BusinessModel { get; set; }
        public string BusinessModel_EN { get; set; }
        public bool CustomProcessing { get; set; }
        public string ProcessingMethods { get; set; }
        public string ProcessingMethods_EN { get; set; }
        public string Imports { get; set; }
        public string Exports { get; set; }
        public string PaidCapital { get; set; }
        public string BusinessRegisteredAddress { get; set; }
        public string BusinessRegisteredAddress_EN { get; set; }
        public System.DateTime DateOfEstablishment { get; set; }
        public string Business { get; set; }
        public string Business_EN { get; set; }
        public string BusinessPictureAddress { get; set; }
        public string EnterpriseLogo { get; set; }
        public int UserId { get; set; }
        public string QualityControl { get; set; }
        public string QualityControl_EN { get; set; }
        public byte SubmitExamineStatus { get; set; }
        public byte UpdateExamineStatus { get; set; }
        public string Nickname { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public byte Status { get; set; }
        public System.DateTime Cdate { get; set; }
        public System.DateTime Lastlogintime { get; set; }
        public string Loginip { get; set; }
        public string Ad_ImgPath { get; set; }
        public string Ad_LogoPath { get; set; }
        public string Ad_Intr { get; set; }
        public byte MerchantType { get; set; }
        public string BankNumber { get; set; }
        public string AccountHolders { get; set; }
        public string Bank { get; set; }
        public string VerifyPhone { get; set; }
        public string GoodNess { get; set; }
        public string Remind { get; set; }
        public string MoreIntro { get; set; }
        public string QQA { get; set; }
        public string QQB { get; set; }
        public string TelephoneA { get; set; }
        public string TelephoneB { get; set; }
        public string MobilePhone { get; set; }
        public string ServiceTime { get; set; }
        public string QQAName { get; set; }
        public string QQBName { get; set; }
        public string ReadBeforeBuy { get; set; }
        public string bindingMPhone { get; set; }
        public bool IsAllowSendMsg { get; set; }
        public string SMSTemplate { get; set; }
        public string Domain { get; set; }
        public Nullable<System.DateTime> BMPhoneTime { get; set; }
        public string HeadTitle { get; set; }
        public Nullable<System.DateTime> VipBeginTime { get; set; }
        public Nullable<System.DateTime> VipEndTime { get; set; }
        public bool ShowOrderPhone { get; set; }
        public Nullable<decimal> CommonShippingLine { get; set; }
        public Nullable<decimal> ShunFengShippingLine { get; set; }
        public Nullable<int> SendAddressId { get; set; }
        public Nullable<byte> SettleMethod { get; set; }
        public Nullable<decimal> CommonExpressGrantsPrice_ChengDu { get; set; }
        public Nullable<decimal> CommonExpressGrantsPrice_SiChuan { get; set; }
        public Nullable<decimal> CommonExpressGrantsPrice_LN_JL_HLJ { get; set; }
        public Nullable<decimal> CommonExpressGrantsPrice_XJ_XZ { get; set; }
        public Nullable<decimal> CommonExpressGrantsPrice_Other { get; set; }
        public Nullable<decimal> ShunFengExpressGrantsPrice_Urgent { get; set; }
        public string MerchantEmail { get; set; }
        public string MerchantContacts { get; set; }
        public string MerchantAddress { get; set; }
        public Nullable<decimal> ShunFengExpressGrantsPrice_NoUrgent { get; set; }
        public Nullable<decimal> ShunFengExpressGrantsPrice_NoUrgent_Other { get; set; }
        public Nullable<decimal> ShunFengExpressGrantsPrice_Urgent_Other { get; set; }
    
        public virtual Industry Industry { get; set; }
        public virtual UserBase UserBase { get; set; }
        public virtual ICollection<Product> Product { get; set; }
    }
}
