//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnterpriseRecommend
    {
        public int Id { get; set; }
        public string EnterpriseName { get; set; }
        public string AnnualTurnover { get; set; }
        public string MainProducts { get; set; }
        public string EnterpriseAddress { get; set; }
        public byte Sort { get; set; }
        public byte Status { get; set; }
        public string EnterpriseName_EN { get; set; }
        public string MainProducts_EN { get; set; }
        public string EnterpriseAddress_EN { get; set; }
        public string UrlLink { get; set; }
        public string AnnualTurnover_EN { get; set; }
    }
}
