//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events_Data
    {
        public int EventsId { get; set; }
        public Nullable<System.DateTime> EventsStartTime { get; set; }
        public Nullable<System.DateTime> EventsEndTime { get; set; }
        public Nullable<byte> Status { get; set; }
        public string ShowBill { get; set; }
        public bool IsShowProductList { get; set; }
        public bool IsShowHotEvents { get; set; }
        public string EventsName { get; set; }
        public string EventsCover { get; set; }
    }
}
