//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventsProducts
    {
        public int Id { get; set; }
        public int ProId { get; set; }
        public int EventsId { get; set; }
        public Nullable<byte> Status { get; set; }
        public byte EventsType { get; set; }
        public decimal EventsChange { get; set; }
        public string EventsRemark { get; set; }
        public int SKUZoneId { get; set; }
        public string ProName { get; set; }
        public string ProCover { get; set; }
        public string BrandName { get; set; }
        public int BrandId { get; set; }
        public int ColorId { get; set; }
        public int SizeId { get; set; }
    }
}
