//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favorites
    {
        public int F_Id { get; set; }
        public int F_ObjectId { get; set; }
        public int F_UserId { get; set; }
        public System.DateTime F_Time { get; set; }
        public byte F_Status { get; set; }
        public byte F_ClientType { get; set; }
    }
}
