//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FreightValAlg
    {
        public int Id { get; set; }
        public Nullable<int> FTId { get; set; }
        public Nullable<byte> Delivery { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<decimal> InitialDose { get; set; }
        public Nullable<double> StartingPrice { get; set; }
        public Nullable<int> Increment { get; set; }
        public Nullable<decimal> IncrementatPrice { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<int> DistrictId { get; set; }
    }
}
