//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FriendLinks
    {
        public int id { get; set; }
        public string linkname { get; set; }
        public string linkurl { get; set; }
        public Nullable<int> sort { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> prval { get; set; }
        public Nullable<int> ipval { get; set; }
        public string logo { get; set; }
    }
}
