//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoldBook
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public byte Status { get; set; }
        public Nullable<decimal> Money { get; set; }
        public int GroupId { get; set; }
        public Nullable<int> UsedId { get; set; }
        public string UsedOrder { get; set; }
        public Nullable<System.DateTime> UsedTime { get; set; }
        public string UsedIP { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public byte LimitOrder { get; set; }
        public decimal LimitMoney { get; set; }
        public byte LimitStyle { get; set; }
        public string LimitRemark { get; set; }
        public bool IsReverse { get; set; }
        public bool IsMixed { get; set; }
        public string GoldRemark { get; set; }
        public int SendUserId { get; set; }
        public Nullable<System.DateTime> ActivateTime { get; set; }
    }
}
