//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Industry
    {
        public Industry()
        {
            this.Enterprise = new HashSet<Enterprise>();
        }
    
        public int IndustryId { get; set; }
        public string IndustryName { get; set; }
        public string IndustryName_EN { get; set; }
    
        public virtual ICollection<Enterprise> Enterprise { get; set; }
    }
}
