//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvitationUser
    {
        public int Id { get; set; }
        public int InvitationParentUid { get; set; }
        public int InvitationToUid { get; set; }
        public System.DateTime InvitationTime { get; set; }
        public bool IsFirstBuying { get; set; }
        public string CashbackInfo { get; set; }
        public string InvitationCode { get; set; }
    }
}
