//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Merchant_GroupOrder
    {
        public int Id { get; set; }
        public string Ordernumber { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> MerId { get; set; }
        public Nullable<System.DateTime> SubOrderTime { get; set; }
        public Nullable<System.DateTime> PayTime { get; set; }
        public Nullable<decimal> PayMoney { get; set; }
        public byte Status { get; set; }
    }
}
