//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public string Email { get; set; }
        public System.DateTime MessageTime { get; set; }
        public string Content { get; set; }
        public string Reply { get; set; }
        public Nullable<System.DateTime> ReplyTime { get; set; }
        public int UserId { get; set; }
        public int EnterpriseUserId { get; set; }
        public bool IsRead { get; set; }
        public int Status { get; set; }
    
        public virtual UserBase UserBase { get; set; }
        public virtual UserBase UserBase1 { get; set; }
    }
}
