//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Title { get; set; }
        public string Title_EN { get; set; }
        public int IndustryId { get; set; }
        public int EnterpriseId { get; set; }
        public string ProductName { get; set; }
        public string ProductName_EN { get; set; }
        public int ProductCount { get; set; }
        public int Count_MeasurementUnit { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Price_Unit { get; set; }
        public int Price_MeasurementUnit { get; set; }
        public string Content { get; set; }
        public string Content_EN { get; set; }
        public string AttachmentName { get; set; }
        public string AttachmentUrl { get; set; }
        public System.DateTime ExpirationTime { get; set; }
        public string Terms { get; set; }
        public string Terms_EN { get; set; }
        public string Port { get; set; }
        public string Port_EN { get; set; }
        public int TermsOfShipment { get; set; }
        public byte Status { get; set; }
        public byte OfferType { get; set; }
        public System.DateTime AddOfferTime { get; set; }
    }
}
