//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPayMoneyRemind
    {
        public int Id { get; set; }
        public int O_Id { get; set; }
        public int U_Id { get; set; }
        public System.DateTime Order_time { get; set; }
        public Nullable<System.DateTime> LastSendTime_phone { get; set; }
        public Nullable<byte> SendPhone_number { get; set; }
        public Nullable<System.DateTime> LastSendTime_email { get; set; }
        public Nullable<byte> SendEmail_number { get; set; }
        public Nullable<System.DateTime> LastSendTime_Message { get; set; }
    }
}
