//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orderinfo
    {
        public int Id { get; set; }
        public string Orernumber { get; set; }
        public Nullable<int> Addressid { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<decimal> Pay_money { get; set; }
        public decimal PaymentMoney { get; set; }
        public Nullable<decimal> Pay_Over { get; set; }
        public Nullable<byte> Pay_Method { get; set; }
        public Nullable<byte> Receive_method { get; set; }
        public Nullable<byte> Pay_status { get; set; }
        public Nullable<System.DateTime> Order_time { get; set; }
        public Nullable<System.DateTime> Pay_time { get; set; }
        public string Receive { get; set; }
        public string TeleNumber { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> Pricing { get; set; }
        public string InterFlowCompany { get; set; }
        public string SendNumber { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public string LeaveMessage { get; set; }
        public string ParentOrderNumber { get; set; }
        public Nullable<int> MerId { get; set; }
        public string LogisticsPinyin { get; set; }
        public Nullable<byte> OrderType { get; set; }
        public Nullable<System.DateTime> Confirm_time { get; set; }
        public Nullable<System.DateTime> AutoConfirm_time { get; set; }
        public Nullable<double> PricesOrdiscounts { get; set; }
        public decimal SendPrice { get; set; }
        public Nullable<byte> UserSendType { get; set; }
        public byte PaymentMode { get; set; }
        public bool IsPayAfterReceive { get; set; }
        public bool IsSendBeforeTelConfirm { get; set; }
        public int FirstShareId { get; set; }
        public Nullable<int> Integral { get; set; }
        public Nullable<decimal> Integral_Money { get; set; }
        public Nullable<bool> IsTakeSelf { get; set; }
        public string InvoiceTitle { get; set; }
        public byte InvoiceContentsType { get; set; }
        public byte Status { get; set; }
        public bool IsSendUrgent { get; set; }
        public bool IsSplitOrder { get; set; }
        public byte SplitSatus { get; set; }
        public decimal SendUrgentMoney { get; set; }
        public int AddressCityId { get; set; }
        public byte SettledType { get; set; }
        public decimal SettledGrantMoney { get; set; }
        public Nullable<System.DateTime> SettledTime { get; set; }
    }
}
