//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_RealPro_Info
    {
        public int Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> PriceId { get; set; }
        public Nullable<int> Userid { get; set; }
        public Nullable<byte> Pstate { get; set; }
        public Nullable<int> Pcount { get; set; }
        public Nullable<System.DateTime> Add_time { get; set; }
        public string Commodity_Cover { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> ColorId { get; set; }
        public Nullable<int> SizeId { get; set; }
        public string CartGuid { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Price_N { get; set; }
    }
}
