//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentCard
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public System.DateTime AddTime { get; set; }
        public byte Status { get; set; }
        public double Money { get; set; }
        public string Remark { get; set; }
        public int GrounpId { get; set; }
        public int UsedId { get; set; }
        public Nullable<System.DateTime> UsedTime { get; set; }
        public string UsedIP { get; set; }
        public byte GUseCount { get; set; }
    }
}
