//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerMark
    {
        public int M_id { get; set; }
        public int U_id { get; set; }
        public int P_id { get; set; }
        public byte P_MarkType { get; set; }
        public byte Fraction { get; set; }
        public System.DateTime CDate { get; set; }
    }
}
