//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerPictrues
    {
        public int Id { get; set; }
        public int Perid { get; set; }
        public string Pic_Name { get; set; }
        public string Pic_Desc { get; set; }
        public string Pic_Path { get; set; }
        public Nullable<System.DateTime> Pic_Time { get; set; }
        public Nullable<byte> Pic_Status { get; set; }
        public Nullable<byte> Pic_Order { get; set; }
        public byte Category { get; set; }
    }
}
