//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProBrowseLog
    {
        public System.DateTime Time { get; set; }
        public int Pid { get; set; }
        public int Bid { get; set; }
        public int STId { get; set; }
        public int TTid { get; set; }
        public int FTid { get; set; }
        public int Type { get; set; }
    }
}
