//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProDataBasic
    {
        public int Id { get; set; }
        public string T_Name { get; set; }
        public Nullable<int> T_TypeDepth1 { get; set; }
        public Nullable<int> T_TypeDepth2 { get; set; }
        public Nullable<int> T_TypeDepth3 { get; set; }
        public string T_Cover { get; set; }
        public Nullable<int> T_Businesses { get; set; }
        public string T_Details { get; set; }
        public string T_SubTitle { get; set; }
        public string KeyWords { get; set; }
        public string Description { get; set; }
        public Nullable<int> T_Status { get; set; }
        public Nullable<int> T_ClickCount { get; set; }
        public int T_SellCount { get; set; }
        public decimal T_AvgScore { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string T_Address { get; set; }
        public Nullable<int> ProvinceID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public Nullable<int> FreightTemplateId { get; set; }
        public Nullable<decimal> ProWeight { get; set; }
        public Nullable<decimal> ProVolume { get; set; }
        public Nullable<int> SKUZoneId { get; set; }
        public string ProductNumber { get; set; }
        public byte WebPageViewTemplate { get; set; }
        public Nullable<int> Integral { get; set; }
        public string shareMsg { get; set; }
        public int BrandId { get; set; }
        public string BarCode { get; set; }
    }
}
