//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductType
    {
        public int Id { get; set; }
        public string Pro_Name { get; set; }
        public int Pro_Parents { get; set; }
        public Nullable<int> Type_Order_Id { get; set; }
        public string UrlName { get; set; }
        public Nullable<byte> Status { get; set; }
        public string Title { get; set; }
        public string Keywords { get; set; }
        public string Description { get; set; }
        public int Depth { get; set; }
        public string WebTypeCover { get; set; }
        public string MobileTypeCover { get; set; }
    }
}
