//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public int EnterpriseId { get; set; }
        public string Title { get; set; }
        public string Details { get; set; }
        public string Title_EN { get; set; }
        public string Details_EN { get; set; }
        public string ProductCover { get; set; }
        public byte Status { get; set; }
        public string Introduction { get; set; }
        public string Introduction_EN { get; set; }
        public string Terms { get; set; }
        public string Terms_EN { get; set; }
        public string Port { get; set; }
        public string Port_EN { get; set; }
        public bool IsRelease { get; set; }
        public string ProductCover_EN { get; set; }
        public decimal Fob_SP { get; set; }
        public decimal Fob_EP { get; set; }
        public string Fob_PriceUnit { get; set; }
        public byte Fob_MeasurementUnit { get; set; }
        public int Batch { get; set; }
        public byte Batch_MeasurementUnit { get; set; }
        public int Supply { get; set; }
        public byte Supply_MeasurementUnit { get; set; }
        public byte Supply_DateUnit { get; set; }
    
        public virtual Enterprise Enterprise { get; set; }
    }
}
