//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProducingTraceableDynamic
    {
        public int Id { get; set; }
        public int ShopCartId { get; set; }
        public int ProductId { get; set; }
        public string PurchaseSource { get; set; }
        public Nullable<System.DateTime> PurchaseTime { get; set; }
        public string ProcessPlace { get; set; }
        public Nullable<System.DateTime> ProcessTime { get; set; }
        public Nullable<System.DateTime> CompleteTime { get; set; }
        public string StoragePlace { get; set; }
        public string StorageMethod { get; set; }
        public Nullable<System.DateTime> EatTime { get; set; }
        public string NotEatKeepMethod { get; set; }
    }
}
