//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProRecommend
    {
        public int Id { get; set; }
        public Nullable<int> Pro_Id { get; set; }
        public string PR_Name { get; set; }
        public string PR_Cover { get; set; }
        public Nullable<double> PR_MinPrice { get; set; }
        public Nullable<double> PR_MinCurrent { get; set; }
        public Nullable<double> PR_MinOriginal { get; set; }
        public Nullable<double> PR_Mark { get; set; }
        public Nullable<byte> PR_MarkStyle { get; set; }
        public string PR_Address { get; set; }
        public Nullable<System.DateTime> PR_StartTime { get; set; }
        public Nullable<int> PR_Type { get; set; }
        public Nullable<System.DateTime> PR_Time { get; set; }
        public string PR_Introduction { get; set; }
        public Nullable<int> PR_OrderById { get; set; }
        public Nullable<int> PR_MerId { get; set; }
        public string PR_HotReply { get; set; }
        public string PR_HotReplyUsername { get; set; }
        public Nullable<int> PR_RepCount { get; set; }
    }
}
