//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProSetType
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int Sort { get; set; }
        public Nullable<bool> IsRealOrNot { get; set; }
        public byte PageType { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<short> CoverWidth { get; set; }
        public Nullable<short> CoverHeight { get; set; }
        public Nullable<int> ShowCount { get; set; }
        public string Remark { get; set; }
        public bool IsShow { get; set; }
    }
}
