//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProSetTypeVal
    {
        public int Id { get; set; }
        public Nullable<int> PSTId { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<int> ProId { get; set; }
        public string ProName { get; set; }
        public string ProCover { get; set; }
        public Nullable<decimal> ProStarPrice { get; set; }
        public byte PageType { get; set; }
        public int Type2 { get; set; }
        public int Type3 { get; set; }
        public int Type4 { get; set; }
        public bool IsRealOrNot { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<int> ReplyCount { get; set; }
        public Nullable<double> AvgScore { get; set; }
        public string SubTitle { get; set; }
        public string SetDescription { get; set; }
    }
}
