//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProSupplier
    {
        public int SupplierId { get; set; }
        public string Name { get; set; }
        public string Contact { get; set; }
        public string TelNumber { get; set; }
        public string Phone { get; set; }
        public string QQ { get; set; }
        public string WWNumber { get; set; }
        public string FaxNumber { get; set; }
        public string Address { get; set; }
        public string Mail { get; set; }
        public string HomeAddress { get; set; }
        public Nullable<int> MerId { get; set; }
        public Nullable<int> OperatorId { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
    }
}
