//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int id { get; set; }
        public int SKUZoneId { get; set; }
        public string ProductNumber { get; set; }
        public string ProName { get; set; }
        public int ColorId { get; set; }
        public int SizeId { get; set; }
        public int ProCount { get; set; }
        public int CellCount { get; set; }
        public decimal AddPrice { get; set; }
        public System.DateTime AddTime { get; set; }
        public string AddRemark { get; set; }
        public int AdminId { get; set; }
        public int SupplierId { get; set; }
        public int MerId { get; set; }
        public byte PurStatus { get; set; }
        public byte Type1 { get; set; }
        public byte Type2 { get; set; }
        public byte Type3 { get; set; }
        public byte Type4 { get; set; }
    }
}
