//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Push_MobileMessage
    {
        public int id { get; set; }
        public string msgcontents { get; set; }
        public byte pushstatus { get; set; }
        public byte pushtype { get; set; }
        public string pushpara { get; set; }
        public Nullable<System.DateTime> pushtime { get; set; }
        public int pushTargetId { get; set; }
    }
}
