//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QJT_PrivateMessage
    {
        public int Id { get; set; }
        public string Contents { get; set; }
        public int SendUser { get; set; }
        public int ReceiveUser { get; set; }
        public bool ReceiveUserIsRead { get; set; }
        public bool SendUserIsDel { get; set; }
        public bool ReceiveUserIsDel { get; set; }
        public string MessageImage { get; set; }
        public System.DateTime SendTime { get; set; }
        public byte Status { get; set; }
        public string ImageMessage { get; set; }
    }
}
