//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QJT_ReplyRemind
    {
        public int Id { get; set; }
        public string Contents { get; set; }
        public int RemindUserId { get; set; }
        public int FromUserId { get; set; }
        public int MsgId { get; set; }
        public System.DateTime RemindTime { get; set; }
        public bool IsRead { get; set; }
        public bool IsDelete { get; set; }
        public byte Status { get; set; }
    }
}
