//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QJT_Messages
    {
        public int Id { get; set; }
        public string Contents { get; set; }
        public System.DateTime SendTime { get; set; }
        public int SendUser { get; set; }
        public int CommunityId { get; set; }
        public int ReplyCount { get; set; }
        public int CollectCount { get; set; }
        public string MsgImagesPath { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<double> Start_Lng { get; set; }
        public Nullable<double> Start_Lat { get; set; }
        public Nullable<double> End_Lng { get; set; }
        public Nullable<double> End_Lat { get; set; }
        public string CarpoolName { get; set; }
        public byte MsgType { get; set; }
        public Nullable<byte> CarpoolType { get; set; }
    }
}
