//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reply
    {
        public int R_id { get; set; }
        public Nullable<int> R_Topic_id { get; set; }
        public string R_Content { get; set; }
        public Nullable<int> R_userid { get; set; }
        public Nullable<int> R_reply { get; set; }
        public byte R_Status { get; set; }
        public Nullable<System.DateTime> R_Ctime { get; set; }
        public Nullable<byte> R_Type { get; set; }
        public byte Is_New { get; set; }
        public byte R_RepType { get; set; }
        public bool IsUserReply { get; set; }
        public int R_Mark { get; set; }
        public bool IsSingleSun { get; set; }
        public Nullable<byte> R_MarkRank { get; set; }
        public int R_ProductId { get; set; }
    }
}
