//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RL_Brand
    {
        public int B_Id { get; set; }
        public string B_Name { get; set; }
        public string B_Logo { get; set; }
        public string B_Cover { get; set; }
        public string B_Introduction { get; set; }
        public string B_IntroductionImage { get; set; }
        public byte B_Status { get; set; }
        public int B_CollectCount { get; set; }
        public string B_BirthPlace { get; set; }
    }
}
