//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchLog
    {
        public int Id { get; set; }
        public string Keyword { get; set; }
        public System.DateTime Time { get; set; }
        public int UId { get; set; }
        public string IP { get; set; }
        public int Type { get; set; }
    }
}
