//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SK_Slider
    {
        public int S_Id { get; set; }
        public string S_Cover { get; set; }
        public string S_Title { get; set; }
        public string S_LinkUrl { get; set; }
        public byte S_LinkType { get; set; }
        public int S_LinkTypeId { get; set; }
        public int S_Sort { get; set; }
        public int S_STId { get; set; }
    }
}
