//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SK_UserCollection
    {
        public int C_Id { get; set; }
        public int C_UserId { get; set; }
        public int C_CollectId { get; set; }
        public byte C_CollectType { get; set; }
        public byte C_Status { get; set; }
    }
}
