//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKUTDataBasic
    {
        public int Id { get; set; }
        public string T_Name { get; set; }
        public Nullable<int> Pro_Type { get; set; }
        public Nullable<int> TB_Type { get; set; }
        public Nullable<int> T_Type { get; set; }
        public Nullable<int> TS_Type { get; set; }
        public string T_Cover { get; set; }
        public Nullable<int> T_Businesses { get; set; }
        public string T_Introduction { get; set; }
        public string T_Remark { get; set; }
        public string KeyWords { get; set; }
        public string Description { get; set; }
        public Nullable<int> T_OrderTimeout { get; set; }
        public Nullable<int> T_Status { get; set; }
        public Nullable<int> T_Set_Sta { get; set; }
        public Nullable<System.DateTime> T_Set_Time { get; set; }
        public Nullable<int> T_ClickCount { get; set; }
        public string T_SMSTemplate { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<int> LastStatus { get; set; }
        public string T_Area { get; set; }
        public string T_FitAge { get; set; }
        public Nullable<System.DateTime> T_StartTime { get; set; }
        public Nullable<System.DateTime> T_EndTime { get; set; }
        public string T_Address { get; set; }
        public string T_Coordinate { get; set; }
        public Nullable<byte> T_SmgType { get; set; }
        public string ProMoteMessge { get; set; }
        public Nullable<bool> IsInvoice { get; set; }
        public Nullable<bool> IsGuarantee { get; set; }
        public string GuaranteeMessage { get; set; }
        public Nullable<bool> IsSpeeDrelease { get; set; }
        public Nullable<bool> IsSevenDayReturn { get; set; }
        public Nullable<bool> IsAfterSaleService { get; set; }
        public Nullable<bool> IsReturnsSafeguard { get; set; }
        public Nullable<int> ProvinceID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public Nullable<int> FreightTemplateId { get; set; }
        public Nullable<decimal> ProWeight { get; set; }
        public Nullable<decimal> ProVolume { get; set; }
        public Nullable<int> SKUTZoneId { get; set; }
    }
}
