//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slider
    {
        public int Id { get; set; }
        public byte Type { get; set; }
        public string ImagePath { get; set; }
        public string Link { get; set; }
        public System.DateTime RTime { get; set; }
        public byte Status { get; set; }
        public string Title { get; set; }
        public string Remark { get; set; }
        public int MerId { get; set; }
        public byte LinkType { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> Sort { get; set; }
        public string SubTitle { get; set; }
        public Nullable<int> ProId { get; set; }
        public string ChildImage1 { get; set; }
        public bool IsShowTitle { get; set; }
        public int EventId { get; set; }
        public decimal EventChange { get; set; }
        public int ClickCount { get; set; }
        public string AllLabel { get; set; }
    }
}
