//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSSendTemplet
    {
        public int Id { get; set; }
        public string SMSContent { get; set; }
        public Nullable<byte> SMSContentType { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<byte> RoleType { get; set; }
        public Nullable<byte> Status { get; set; }
    }
}
