//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Sucool_DB_Entities : DbContext
    {
        public Sucool_DB_Entities()
            : base("name=Sucool_DB_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AdminUsers> AdminUsers { get; set; }
        public DbSet<Aftersales> Aftersales { get; set; }
        public DbSet<AreaData> AreaData { get; set; }
        public DbSet<BalanceOfPaymentsDetails> BalanceOfPaymentsDetails { get; set; }
        public DbSet<BalDetail> BalDetail { get; set; }
        public DbSet<ChatMessage> ChatMessage { get; set; }
        public DbSet<Consult> Consult { get; set; }
        public DbSet<County> County { get; set; }
        public DbSet<CouponsInvalidRemind> CouponsInvalidRemind { get; set; }
        public DbSet<DLY_Admin> DLY_Admin { get; set; }
        public DbSet<Dly_CellsMenu> Dly_CellsMenu { get; set; }
        public DbSet<DLy_Limits> DLy_Limits { get; set; }
        public DbSet<Edm> Edm { get; set; }
        public DbSet<EdmImportData> EdmImportData { get; set; }
        public DbSet<EmailBook> EmailBook { get; set; }
        public DbSet<Enterprise> Enterprise { get; set; }
        public DbSet<EnterpriseRecommend> EnterpriseRecommend { get; set; }
        public DbSet<ErrorStatus> ErrorStatus { get; set; }
        public DbSet<EventRemind> EventRemind { get; set; }
        public DbSet<Events_Data> Events_Data { get; set; }
        public DbSet<EventsProducts> EventsProducts { get; set; }
        public DbSet<FailLog> FailLog { get; set; }
        public DbSet<FAQ> FAQ { get; set; }
        public DbSet<Favorites> Favorites { get; set; }
        public DbSet<Feedback> Feedback { get; set; }
        public DbSet<FreightTemplate> FreightTemplate { get; set; }
        public DbSet<FreightValAlg> FreightValAlg { get; set; }
        public DbSet<FriendLinks> FriendLinks { get; set; }
        public DbSet<GoldBook> GoldBook { get; set; }
        public DbSet<GoldLimit> GoldLimit { get; set; }
        public DbSet<HelpCenter> HelpCenter { get; set; }
        public DbSet<HelpSite> HelpSite { get; set; }
        public DbSet<HotSearch> HotSearch { get; set; }
        public DbSet<Industry> Industry { get; set; }
        public DbSet<InstallLog> InstallLog { get; set; }
        public DbSet<Integral_Details> Integral_Details { get; set; }
        public DbSet<InvitationUser> InvitationUser { get; set; }
        public DbSet<LogisticsCompany> LogisticsCompany { get; set; }
        public DbSet<Merchant_CellsMenu> Merchant_CellsMenu { get; set; }
        public DbSet<Merchant_Group> Merchant_Group { get; set; }
        public DbSet<Merchant_Group_Limits> Merchant_Group_Limits { get; set; }
        public DbSet<Merchant_GroupOrder> Merchant_GroupOrder { get; set; }
        public DbSet<MerchartChild> MerchartChild { get; set; }
        public DbSet<Message> Message { get; set; }
        public DbSet<Offer> Offer { get; set; }
        public DbSet<Order_RealPro_Info> Order_RealPro_Info { get; set; }
        public DbSet<OrderAddress> OrderAddress { get; set; }
        public DbSet<Orderinfo> Orderinfo { get; set; }
        public DbSet<OrderPayMoneyRemind> OrderPayMoneyRemind { get; set; }
        public DbSet<OrderProcessMessage> OrderProcessMessage { get; set; }
        public DbSet<PaymentCard> PaymentCard { get; set; }
        public DbSet<PerMark> PerMark { get; set; }
        public DbSet<PerPictrues> PerPictrues { get; set; }
        public DbSet<PriNum_Data> PriNum_Data { get; set; }
        public DbSet<ProBrowseLog> ProBrowseLog { get; set; }
        public DbSet<ProDataBasic> ProDataBasic { get; set; }
        public DbSet<ProducingTraceableDynamic> ProducingTraceableDynamic { get; set; }
        public DbSet<Product> Product { get; set; }
        public DbSet<ProductPicture> ProductPicture { get; set; }
        public DbSet<ProductType> ProductType { get; set; }
        public DbSet<ProRecommend> ProRecommend { get; set; }
        public DbSet<ProRecord> ProRecord { get; set; }
        public DbSet<ProSetType> ProSetType { get; set; }
        public DbSet<ProSetTypeVal> ProSetTypeVal { get; set; }
        public DbSet<ProSupplier> ProSupplier { get; set; }
        public DbSet<ProTypeAttributeValue> ProTypeAttributeValue { get; set; }
        public DbSet<Purchase> Purchase { get; set; }
        public DbSet<Push_MobileMessage> Push_MobileMessage { get; set; }
        public DbSet<Push_MobileToken> Push_MobileToken { get; set; }
        public DbSet<QJT_Community> QJT_Community { get; set; }
        public DbSet<QJT_CommunityUsers> QJT_CommunityUsers { get; set; }
        public DbSet<QJT_FollowUser> QJT_FollowUser { get; set; }
        public DbSet<QJT_Images> QJT_Images { get; set; }
        public DbSet<QJT_MessageReplys> QJT_MessageReplys { get; set; }
        public DbSet<QJT_Messages> QJT_Messages { get; set; }
        public DbSet<QJT_MobileAddr> QJT_MobileAddr { get; set; }
        public DbSet<QJT_PrivateMessage> QJT_PrivateMessage { get; set; }
        public DbSet<QJT_ReplyRemind> QJT_ReplyRemind { get; set; }
        public DbSet<QJT_UserCollect> QJT_UserCollect { get; set; }
        public DbSet<Recommend> Recommend { get; set; }
        public DbSet<Reply> Reply { get; set; }
        public DbSet<RL_Brand> RL_Brand { get; set; }
        public DbSet<RL_BrandCollection> RL_BrandCollection { get; set; }
        public DbSet<RL_BrandPictrues> RL_BrandPictrues { get; set; }
        public DbSet<RL_ProductIntroduction> RL_ProductIntroduction { get; set; }
        public DbSet<SearchLog> SearchLog { get; set; }
        public DbSet<SearchRecord> SearchRecord { get; set; }
        public DbSet<ShareLog> ShareLog { get; set; }
        public DbSet<SiteVerCode> SiteVerCode { get; set; }
        public DbSet<SK_Slider> SK_Slider { get; set; }
        public DbSet<SK_SliderType> SK_SliderType { get; set; }
        public DbSet<SK_UserCollection> SK_UserCollection { get; set; }
        public DbSet<SKUTDataBasic> SKUTDataBasic { get; set; }
        public DbSet<SKUTTypeAttributeValue> SKUTTypeAttributeValue { get; set; }
        public DbSet<SKUZone> SKUZone { get; set; }
        public DbSet<Slider> Slider { get; set; }
        public DbSet<SliderType> SliderType { get; set; }
        public DbSet<SMSSendTemplet> SMSSendTemplet { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TransErrorLog> TransErrorLog { get; set; }
        public DbSet<TypeAttribute> TypeAttribute { get; set; }
        public DbSet<TypeAttributeValue> TypeAttributeValue { get; set; }
        public DbSet<UrlRewRules> UrlRewRules { get; set; }
        public DbSet<UserBase> UserBase { get; set; }
        public DbSet<UserDrawRecord> UserDrawRecord { get; set; }
        public DbSet<UserMessage> UserMessage { get; set; }
        public DbSet<VestUser> VestUser { get; set; }
        public DbSet<Video> Video { get; set; }
        public DbSet<VideoBlockFiles> VideoBlockFiles { get; set; }
        public DbSet<VideoUploadFile> VideoUploadFile { get; set; }
    }
}
