//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeAttribute
    {
        public int Id { get; set; }
        public Nullable<int> ClassId { get; set; }
        public string Name { get; set; }
        public Nullable<byte> ShowType { get; set; }
        public Nullable<byte> ManagerType { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<byte> Sort { get; set; }
        public Nullable<System.DateTime> SortUpdateTime { get; set; }
        public Nullable<byte> Type { get; set; }
        public Nullable<bool> IsRequired { get; set; }
    }
}
