//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDrawRecord
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int AwardsId { get; set; }
        public string AwardsName { get; set; }
        public string DrawName { get; set; }
        public System.DateTime WinningTime { get; set; }
        public decimal Money { get; set; }
        public string UserName { get; set; }
    }
}
