//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBase
    {
        public UserBase()
        {
            this.Enterprise = new HashSet<Enterprise>();
            this.Message = new HashSet<Message>();
            this.Message1 = new HashSet<Message>();
        }
    
        public int Id { get; set; }
        public string Email { get; set; }
        public string PassWord { get; set; }
        public string NickName { get; set; }
        public System.DateTime RegisterTime { get; set; }
        public byte RegisterType { get; set; }
        public System.DateTime LastLoginTime { get; set; }
        public string LastLoginIp { get; set; }
        public byte RegisterCountry { get; set; }
        public byte Status { get; set; }
        public string OpenKey_QQ { get; set; }
        public string OpenKey_SinaWB { get; set; }
        public string D_Head { get; set; }
        public byte D_UserType { get; set; }
        public Nullable<int> D_point { get; set; }
        public decimal D_AccBalance { get; set; }
        public string D_MobilePhone { get; set; }
        public int CommunityId { get; set; }
        public string CommunityFollow { get; set; }
        public Nullable<int> ShareUserId { get; set; }
        public Nullable<int> MsgLastReadId { get; set; }
        public Nullable<int> CarpoolMsgLastReadId { get; set; }
        public byte D_Sex { get; set; }
        public Nullable<System.DateTime> D_Birthday { get; set; }
        public bool IsEmailChecked { get; set; }
        public string OpenKey_WX { get; set; }
        public byte RegisterClientType { get; set; }
        public string Taste { get; set; }
        public byte Marriage { get; set; }
        public byte MonthlyIncome { get; set; }
        public string InvitationedCode { get; set; }
        public string MyInvitationCode { get; set; }
        public bool IsFirstBuying { get; set; }
    
        public virtual ICollection<Enterprise> Enterprise { get; set; }
        public virtual ICollection<Message> Message { get; set; }
        public virtual ICollection<Message> Message1 { get; set; }
    }
}
