//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoBlockFiles
    {
        public int Id { get; set; }
        public int Fid { get; set; }
        public string MD5 { get; set; }
        public string FileName { get; set; }
        public Nullable<int> Chunk { get; set; }
        public System.DateTime PostedTime { get; set; }
        public Nullable<int> Uid { get; set; }
    }
}
