//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public int VideoId { get; set; }
        public string VideoPath { get; set; }
        public string Cover { get; set; }
        public System.DateTime UploadTime { get; set; }
        public int UploadUser { get; set; }
        public int PlayingTime { get; set; }
        public int PlayingCounts { get; set; }
        public byte VideoStatus { get; set; }
        public string VideoDomainName { get; set; }
        public int EnterpriseId { get; set; }
        public int ProductId { get; set; }
        public byte VideoGroup { get; set; }
        public string Cover_EN { get; set; }
        public string VideoPath_EN { get; set; }
        public int PlayingTime_EN { get; set; }
        public int PlayingCounts_EN { get; set; }
        public int MerchartId { get; set; }
    }
}
